server:
  port: 8098
spring:
  application:
    name: microservice
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: 182.28.0.11
#      database: product-servicer_db
      port: 27017
