version: '2'
networks:
  mired2:
    ipam:
      config:
        - subnet: 182.28.0.0/16
          gateway: 182.28.0.1
services:
  db:
    image: bitnami/mongodb:latest
    container_name: mongo_DB
    networks:
      mired2:
        ipv4_address: 182.28.0.11
    ports:
      - "27017:27017"
    expose:
      - 27017
  app-tutorials:
    image: fransantana0522/tutoriales:1
    container_name: tutoriales
    networks:
      mired2:
        ipv4_address: 182.28.0.12
    expose:
      - 80
    ports:
      - "80:8098"
    depends_on:
      - db